@startuml
title ListApplications Diagram (CandidateApp)_US3001

actor Candidate as actor #orange
box "CandidateApp" #LightGreen
participant ":NotificationsUI" as ui <<presentation>>
end box

box Core #lightblue
participant ":CommunicationController" as com <<application>>
participant ":CommunicationService" as service <<service>>
participant ":Translator" as translator
participant ":Messenger" as messenger
end box

participant "FollowUpServer" as server #orange


activate actor
actor -> ui : Requests to be notified in his application \nwhen the state of one of his applications \nchanges its state.
activate ui
ui -> com**: create()
activate com
ui -> com: listAllNotificationJobApplication()
com -> service**: create()
activate service
com -> service: listAllNotificationJobApplication()
service -> translator: encode(1, MessageCode.LIST_NOTIF_JOB_APPLICATIONS, null, null)
activate translator
translator --> service:  byte[] message
deactivate translator
service -> messenger: sendMessage(message)
activate messenger
messenger -> server
server --> messenger
service -> messenger: receiveMessage()
deactivate messenger
service -> translator: decodeCode(response)
activate translator
translator --> service: MessageCode
deactivate translator

alt MessageCode.SHOW_NOTIF_JOB_APPLICATIONS
service -> translator: decodeData1(response)
activate translator
translator --> service: byte[] data
deactivate translator
service --> com: List<String> notifications
com --> ui: List<String> notifications

loop for each jobApplications
ui --> actor: shows notifications
end

else
service --> com: error listing
deactivate service
com --> ui: error listing
deactivate com
ui --> actor: Shows error while displaying the notifications!
end


@enduml