@startuml
title Connection Diagram (CustomerApp)_US3002

actor Customer as actor
box "CustomerApp" #LightGreen
participant ":CustomerApp" as app
end box

box Core #lightblue
participant ":ComunicationController" as com <<application>>
participant ":CommunicationService" as service <<service>>
participant ":Messenger" as messenger
participant ":Translator" as translator
end box

participant "FollowUpServer" as server #orange

activate actor
actor -> app : asks to set the comunication
activate app
app -> com : initializeComunication(socket)
activate com
com -> service : initializeComunication(socket)
activate service
service -> messenger **: create()
deactivate service
deactivate com
app -> com : testConnection()
activate com
com -> service : testConnection()
activate service
service -> translator: encode(1, MessageCode.COMMTEST, null, null)
activate translator
translator --> service : byte[] message
deactivate translator
service -> messenger: sendMessage(message)
activate messenger
messenger -> server
activate server
server -> messenger
deactivate server
service -> messenger: receiveMessage()
messenger --> service: byte[] receiveMessage
deactivate messenger
service -> translator: decodeCode(response)
activate translator
translator --> service: MessageCode
deactivate translator
service --> com: MessageCode
deactivate service
com --> app: MessageCode
deactivate com

alt MessageCode.ACK
app --> actor: Connection established
else MessageCode.ERR
app --> actor: Connection refused
end




@enduml