@startuml

title Use Case Diagram

left to right direction

actor Admin
actor Operator
actor CustomerManager
actor LanguageEngineer
actor Candidate
actor Customer
actor ProductOwner

skinparam usecase {
    BackgroundColor LightBlue
    ArrowColor Black
    BorderColor Black
    FontColor Black
    FontSize 14
}

skinparam title {
    FontSize 30
}

rectangle BackOffice {

    'SPRINT B
    'US 1000
    usecase "Register Users" as 1000.1
    usecase "Disable Users" as 1000.2
    usecase "Enable Users " as 1000.3
    usecase "List Users" as 1000.4

    Admin -- 1000.1
    Admin -- 1000.2
    Admin -- 1000.3
    Admin -- 1000.4
    CustomerManager -- 1000.1
    Operator -- 1000.1

    'US 1001
    usecase "Register Customers" as 1001

    CustomerManager -- 1001

    'US 1002
    usecase "Register Job Opening" as 1002

    CustomerManager -- 1002

    'US 2000a
    usecase "Register Candidate" as 2000a

    Operator -- 2000a

    'US 2002
    usecase "Register an Application of a Candidate" as 2002.1
    usecase "Import all files received" as 2002.2
    Operator -- 2002.1
    Operator -- 2002.2

    'US 1005
    usecase "List all applications for a Job Opening" as 1005

    CustomerManager -- 1005

    'US 1006
    usecase "Display all the personal data of a Candidate" as 1006
    CustomerManager -- 1006

   'US 1008
    usecase "Deploy a Plugin" as 1008.1
    usecase "Configure a Plugin" as 1008.2

    LanguageEngineer -- 1008.1
    LanguageEngineer -- 1008.2

    'US 1009
    usecase "Select one Requirement Specification" as 1009.1

    CustomerManager -- 1009.1

    usecase "Select one Job Opening" as 1009.2

    CustomerManager -- 1009.2

    usecase "Associate the Job Opening with the Requirement Specification" as 1009.3

    CustomerManager -- 1009.3

   'US 1011
       usecase "Select one Interview Model Specification" as 1011.1

       CustomerManager -- 1009.1

       usecase "Associate the Job Opening with the Interview Model" as 1009.3

       CustomerManager -- 1009.3

    'US 1012
    usecase "Generate and Export a Template Text File \nfor Requirements Specification" as 1012

    CustomerManager -- 1012


    'US 2003
    usecase "Generate and Export a Template Text File for Interviews" as 2003


    Operator -- 2003



    'SPRINT C
    'US 1013
    usecase "Rank the candidates for a Job Opening" as 1013
    CustomerManager -- 1013

    'US 1010
    usecase "Setup phases of the process for a Job Opening" as 1010.1
    usecase "Open or Close phases of the process for a Job Opening" as 1010.2

    CustomerManager -- 1010.1
    CustomerManager -- 1010.2

    'US 1015
    usecase "Verification of Requirements" as 1015

    CustomerManager -- 1015

    'US 1016
    usecase "Notify Candidates" as 1016

    CustomerManager -- 1016

    'US 1017
    usecase "Upload a Text File with the Candidate responses" as 1017

    CustomerManager -- 1017

    'US 1018
    usecase "Evaluates (grades) the Interviews for a Job Opening" as 1018

    CustomerManager -- 1018

    'US 1019
    usecase "Ordered list of Candidates, using the\n Job Interview Points (grades)" as 1019

    CustomerManager -- 1019

    'US 1020
    usecase "Publish the results of the selection \nog Candidates for a Job Opening" as 1020

    CustomerManager -- 1020

    'US 2004
    usecase "Text File with the data fields (requirements)" as 2004

    Operator -- 2004

    'US 4000
    usecase "Top 20 of the most referenced words in the files uploaded\n by a candidate and where they are in the document" as 4000

    CustomerManager -- 4000

}


rectangle CandidateApp {

    'SPRINT C
    'US 3000
    usecase "List all my applications and their state" as 3000

        Candidate --- 3000

    'US 3001
    usecase "Notified in my Application when the state \nof one of my applications changes" as 3001

        Candidate --- 3001

}


rectangle ApplicationsFileBot {

    'SPRINT B & C
    'US 2001
    usecase "Process the files produced by the Applications Email Bot" as 2001
    ProductOwner -- 2001

}

rectangle CustomerApp {

    'SPRINT C
    'US 3002
    usecase "List all my Job Openings, including Job Reference, Position,\n Active Since and Number of Applicants" as 3002

        Customer --- 3002
}

@enduml