@startuml

title <size:20>Sequence Diagram - Activate - UC 1000.3</size>

skinparam monochrome false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor Admin as Actor #lightblue
participant ":ActivateUserUI" as UI <<presentation>>
participant ":ActivateController" as Controller <<application>>
participant ":UserRepository" as Repository <<repository>>

Actor -> UI: List All Users
activate Actor

activate UI
    UI -> Controller**: create


    UI -> Controller: deactivatedUsers()
    activate Controller
        Controller -> Repository: findByActive(false)


    activate Repository
    Repository-->Controller: Deactivated Users
    deactivate Repository


            Controller --> UI: Deactivated Users
     deactivate Controller

     loop option != 0
             UI -> Actor: Show List\nof Deactivated Users
             Actor --> UI: Enters option to activate
         end

    UI -> Controller: activateUser(option - 1)

    activate Controller

    Controller -> Repository:activateUser(user)
    activate Repository

    Repository --> Repository:save(user)


    deactivate Controller


        UI-->Actor: shows sucess
deactivate Repository
deactivate UI
deactivate Actor
@enduml