@startuml

title <size:20>Sequence Diagram - Deactivate - UC 1000.2</size>

skinparam monochrome false
skinparam packageStyle rect
skinparam defaultFontName FG Virgil
skinparam shadowing false

actor Admin as Actor #lightblue
participant ":DeactivateUserUI" as UI <<presentation>>
participant ":DeactivateUserController" as Controller <<application>>
participant ":UserRepository" as Repository <<repository>>

Actor -> UI: List All Users
activate Actor

activate UI
    UI -> Controller**: create


    UI -> Controller: activatedUsers()
    activate Controller
        Controller -> Repository: findByActive(true)


    activate Repository
    Repository-->Controller: Activated Users
    deactivate Repository


            Controller --> UI: Activated Users
     deactivate Controller

     loop option != 0
             UI -> Actor: Show List\nof Activated Users
             Actor --> UI: Enters option to deactivate
         end

    UI -> Controller: deactivateUser(option - 1)

    activate Controller

    Controller -> Repository:deactivateUser(user)
    activate Repository

    Repository --> Repository:save(user)


    deactivate Controller


        UI-->Actor: shows sucess
deactivate Repository
deactivate UI
deactivate Actor
@enduml